#!/usr/bin/env python
import os
import signal

from supervisor import childutils

"""
https://stackoverflow.com/a/37527488/906265

Supervisor event listener that makes suicide if `PROCESS_STATE_FATAL` is emitted
"""


def main():
    while True:
        headers, payload = childutils.listener.wait()
        childutils.listener.ok()
        if headers['eventname'] != 'PROCESS_STATE_FATAL':
            continue
        os.kill(os.getppid(), signal.SIGTERM)


if __name__ == "__main__":
    main()